title: Pizza party
hero_image: images/banner.png
description: Make a pizza-clicker game in this Code Club arcade project.
listed: true
pdf: false
steps:
  - title: What you will make
  - title: Make the clicker
    completion:
      - engaged
  - title: Add the first equipment
  - title: Add more equipment
  - title: Add a helper
    completion:
      - internal
  - title: Add a second helper
  - title: Add a backdrop
    completion:
      - external
  - title: Animate the equipment
  - title: Animate the helpers
